added outputs command to get a set of stack outputs as JSON

diff --git a/bin/cfd b/bin/cfd
--- a/bin/cfd
+++ b/bin/cfd
@@ -31,7 +31,8 @@ display_help() {
     cfd package <template> <output-template> <s3-bucket> <s3-prefix?>  Package a template for deployment
     cfd plan <stack> <template> <params?>                              Plan changes for a stack
     cfd apply <stack> <template> <params?>                             Apply changes to a stack
-    cfd tail <stack>                                                   Tail latest stack events
+    cfd tail <stack> <delay?>                                          Tail latest stack events
+    cfd outputs <stack>                                                Print a stack's outputs as JSON
 
   Options:
 
@@ -46,6 +47,7 @@ display_help() {
     p   plan
     a   apply
     t   tail
+    o   outputs
 
 EOF
 }
@@ -73,7 +75,13 @@ _get_stack_status () {
   local stack_name=$1
 
   # Catch and forward exit code
-  result=`aws cloudformation describe-stacks --stack-name $stack_name | jq -c -r .Stacks[0].StackStatus`
+  result=`aws cloudformation describe-stacks \
+    --stack-name $stack_name \
+    --query 'Stacks[0].StackStatus' \
+    --output text \
+    --max-items 1 \
+    2>&1`
+
   exit_code=$?
 
   if [ "$exit_code" -eq 0 ]; then
@@ -248,6 +256,7 @@ cfd_apply() {
 cfd_tail() {
   test -z $1 && abort "stack name required"
   local stack_name=$1
+  local delay=${2:-3}
   local last_event
   local last_event_id
   local stack_status
@@ -286,7 +295,7 @@ cfd_tail() {
       log tail "$details"
     fi
 
-    sleep 3
+    sleep $delay
 
     stack_status=`_get_stack_status $stack_name`
 
@@ -312,6 +321,31 @@ cfd_tail() {
 }
 
 #
+# Get the outputs for a stack.
+# cfd_tail <stack-name>
+#
+
+cfd_outputs() {
+  test -z $1 && abort "stack name required"
+  local stack_name=$1
+  local outputs=
+
+  result=`aws cloudformation describe-stacks \
+    --stack-name $stack_name \
+    --query 'Stacks[0].Outputs' \
+    --max-items 1 \
+    2>&1`
+
+  if [ "$?" -eq 0 ]; then
+    outputs=`echo $result | jq -r 'reduce .[] as $i ({}; .[$i.OutputKey] = $i.OutputValue)'`
+
+    echo "$outputs"
+  else
+    abort "$result"
+  fi
+}
+
+#
 # Handle arguments.
 #
 
@@ -327,7 +361,8 @@ else
       k|package) shift; cfd_package $@; exit ;;
       p|plan) shift; cfd_plan $@; exit ;;
       a|apply) shift; cfd_apply $@; exit ;;
-      t|tail) cfd_tail $2; exit ;;
+      t|tail) shift; cfd_tail $@; exit ;;
+      o|outputs) cfd_outputs $2; exit ;;
       *) display_help; exit ;;
     esac
     shift
